server:
  port: 9000
spring:
  application:
    name: eureka-client
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #setting username and password 
      defaultZone: http://admin:admin@localhost:1000/eureka/
      
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.cloud: DEBUG
        
                
 
