server:
  port: 9006
spring:
  application:
    name: hystrix-turbine
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #setting username and password
      defaultZone: http://admin:admin@localhost:1000/eureka/
      #defaultZone: http://localhost:1000/eureka/
      
turbine:
  aggregator:
    clusterConfig: default
  appConfig: hystrix-consume
  clusterNameExpression: "'default'"
  