server:
  port: 1000

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
  
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
    #insert username and password
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eurela/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eurela/
