server:
  port: 8000
management:
  context-path: /hello
  
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    secure-health-check-url: ${management.context-path}/health
    #设置可以使用ip进行访问
    prefer-ip-address: true
    metadata-map:
      zone: shanghai
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
          
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update  
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud
    username: root
    password: 123
  application:
    name: eureka-server
  thymeleaf:
    prefix: classpath\:/templates/
    
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    